
//variables
@host = http://localhost
@port = 7005

//GET {{Restaurants.API_HostAddress}}/api/restaurants
//concatenating the variables
@Restaurants_API_HostAddress = {{host}}:{{port}}


GET http://localhost:5256/weatherforecast

//specifying an http header
Accept: application/json
ProjectUrl:{{$ProjectUrl}}
Guid: {{$guid}}
LocalDate: {{$localDatetime rfc1123}}
Random-int: {{$randomInt}}

GET {{Restaurants_API_HostAddress}}/api/restaurants/1